#ifndef CAIRO_FEATURES_H
#define CAIRO_FEATURES_H

#define CAIRO_HAS_FT_FONT 0
#define CAIRO_HAS_IMAGE_SURFACE 1
#define CAIRO_HAS_PDF_SURFACE 0
#define CAIRO_HAS_PNG_FUNCTIONS 1
#define CAIRO_HAS_PS_SURFACE 0
#define CAIRO_HAS_SVG_SURFACE 0
#define CAIRO_HAS_USER_FONT 0
#define CAIRO_HAS_XLIB_SURFACE 0
#define CAIRO_HAS_XLIB_XRENDER_SURFACE 0
#define CAIRO_HAS_WIN32_SURFACE 0 ///< tangbo
#define CAIRO_HAS_WIN32_FONT 0 ///< tangbo

#define CAIRO_HAS_SCRIPT_SURFACE 0
#define CAIRO_HAS_XML_SURFACE 0
#define CAIRO_HAS_TEE_SURFACE 0

#if TIROS_QT_PLATFORM

#define CAIRO_HAS_QT_SURFACE 0//fengfx7.5
#define CAIRO_HAS_EGL_FUNCTIONS 1
#define CAIRO_HAS_GLESV2_SURFACE 0
#define CAIRO_HAS_GL_SURFACE 1

#elif TIROS_ANDROID_PLATFORM || TIROS_IOS_PLATFORM

#define CAIRO_HAS_QT_SURFACE 0
#define CAIRO_HAS_GLESV2_SURFACE 1
#define CAIRO_HAS_EGL_FUNCTIONS 1

#else
//    #error Must define platform
#endif/*QT or ANDROID or IOS*/

#endif
